version: '3.7'

services:
  web:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/src
      - /src/node_modules
    command: yarn run start -- --host 0.0.0.0

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - /src/node_modules
    command: yarn run start-api -- --host 0.0.0.0
